Update patch set 7
Patch Set 7:

seem to be hitting vpp dep version issues here:
Error: Package: honeycomb-1.17.04-2048.noarch (/honeycomb-1.17.04-2048.noarch)
           Requires: vpp = 17.04-release
Error: Package: honeycomb-1.17.04-2048.noarch (/honeycomb-1.17.04-2048.noarch)
           Requires: vpp-plugins = 17.04-release

Patch-set: 7