Update patch set 11
Patch Set 11: Code-Review-1

(3 comments)

I think this needs to be refactored to just be another method call during the parse_network_settings call to modify the network-environment yaml file using pyyaml.  Also, there needs to be better error checking as we got a traceback in the jenkins verify:

[34mNetwork Environment set for Deployment: [m
Traceback (most recent call last):
  File "/home/jenkins-ci/opnfv/slave_root/workspace/apex-verify-master/build/lib/python/apex-python-utils.py", line 157, in <module>
    args.func(args)
  File "/home/jenkins-ci/opnfv/slave_root/workspace/apex-verify-master/build/lib/python/apex-python-utils.py", line 55, in build_netenv_template
    netenv['parameter_defaults']['ControlPlaneSubnetCidr'] = settings.admin_network.cidr.prefixlen
AttributeError: 'NetworkSettings' object has no attribute 'admin_network'

Patch-set: 11
Label: Code-Review=-1