Update patch set 7
Patch Set 7:

I'm not sure why the functest gate fails, but it looks like some issue with glance:
ConflictException: ConflictException: 409: Client Error for url: http://192.168.37.10:9292/v2/images/19151644-181f-4120-996a-25a7805ae284/file, <html>
 <head>
  <title>409 Conflict</title>
 </head>
 <body>
  <h1>409 Conflict</h1>
  Image status transition from saving to saving is not allowed<br /><br />

I'm going to go ahead and merge this patch and we can see how the scenario does in daily functest.

Patch-set: 7