Update patch set 4
Patch Set 4: Code-Review-1

> This is the error.
 > 
 > Traceback (most recent call last):
 > File "/bin/opnfv-deploy", line 10, in <module>
 > sys.exit(main())
 > File "/usr/lib/python3.4/site-packages/apex/deploy.py", line 386,
 > in main
 > APEX_TEMP_DIR, branch)
 > File "/usr/lib/python3.4/site-packages/apex/builders/common_builder.py",
 > line 215, in add_upstream_patches
 > virt_utils.virt_customize(virt_ops, image)
 > File "/usr/lib/python3.4/site-packages/apex/virtual/utils.py", line
 > 193, in virt_customize
 > stderr=subprocess.STDOUT))
 > File "/usr/lib64/python3.4/subprocess.py", line 617, in
 > check_output
 > raise CalledProcessError(retcode, process.args, output=output)
 > subprocess.CalledProcessError: Command '['virt-customize',
 > '--install', 'patch', '--upload', '/tmp/apex_tmpm__rbqfj/Ic08ff58b10d4fa7116163be1f7fce57879cee8c5.patch:/usr/lib/python2.7/site-packages/',
 > '--run-command', 'cd /usr/lib/python2.7/site-packages/ && patch -p1
 > < Ic08ff58b10d4fa7116163be1f7fce57879cee8c5.patch', '-a',
 > '/home/jenkins-ci/upstream_cache/queens/undercloud_mod.qcow2']'
 > returned non-zero exit status 1
 > 
 > 
 > Is that the files are misplaced ?

It's because the file is actually placed here when the package is installed:
/usr/share/openstack-tripleo-common-containers/container-images/overcloud_containers.yaml.j2

Tripleo common python is also installed into:
/usr/lib/python2.7/site-packages/tripleo_common/

So we can detect which files are modified and split the patch file and then apply it to the correct directories. Alternatively since this is a one line patch we could just use an ansible task to insert the extra line during undercloud ansible configuration. I don't have time to work this right now so maybe Trinath you could take it over.

Patch-set: 4
Label: Code-Review=-1