Update patch set 1
Patch Set 1:

reverify

Not sure why this failed:
ERROR: Authentication failed. Please try again with option --include-password or export HEAT_INCLUDE_PASSWORD=1
Authentication required

I wouldn't think adding an IP to compute nodes would fail auth.

Patch-set: 1